version: '3.7'
services:
  mongodb:
    image: mongo:latest
#    environment:
#      MONGO_INITDB_ROOT_USERNAME: root
#      MONGO_INITDB_ROOT_PASSWORD: password
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data_container:/data/db

  solr:
    image: solr
    ports:
      - "8983:8983"
    volumes:
      - data:/var/solr
    command:
      - solr-precreate
      - gettingstarted

  api:
    image: pisproject-test
    ports:
      - "8080:8080"
    build:
      context: .
      dockerfile: Dockerfile

volumes:
  mongodb_data_container:
  data: